version: '3.3'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: p4tr1m0n10
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
volumes:
  mysql_db_data_container:
